# Generated by Django 4.1.2 on 2022-10-11 03:59

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=api.models.generate_code, editable=False, max_length=50)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=50, null=True)),
                ('pursuing', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Arc', 'B.Arc'), ('B.Des', 'B.Des'), ('BCA', 'BCA'), ('B.Sc', 'B.Sc'), ('B.A', 'B.A'), ('B.Com', 'B.Com'), ('BBA', 'BBA'), ('B.E', 'B.E'), ('M.Tech', 'M.Tech'), ('M.Des', 'M.Des'), ('MCA', 'MCA'), ('M.Sc', 'M.Sc'), ('M.A', 'M.A'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('MBA', 'MBA'), ('M.S', 'M.S'), ('LLB', 'LLB'), ('B.S(Eco)', 'B.S(Eco)')], default='None', max_length=50, null=True)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CTOHuntProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_round_cleared', models.IntegerField(default=0)),
                ('round1Status', models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50)),
                ('round2Status', models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50)),
                ('round3Status', models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50)),
                ('result', models.CharField(default='Rejected', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
