# Generated by Django 4.1.2 on 2022-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mockpitchprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockpitchprogress',
            name='selection_status',
        ),
        migrations.AddField(
            model_name='mockpitchprogress',
            name='result',
            field=models.CharField(default='Rejected', max_length=200),
        ),
        migrations.AddField(
            model_name='mockpitchprogress',
            name='round1Status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50),
        ),
        migrations.AddField(
            model_name='mockpitchprogress',
            name='round2Status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50),
        ),
        migrations.AddField(
            model_name='mockpitchprogress',
            name='round3Status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50),
        ),
        migrations.AddField(
            model_name='mockpitchprogress',
            name='round4Status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Not Started', max_length=50),
        ),
    ]
