# Generated by Django 4.1.2 on 2022-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mockpitchprogress_selection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
